version: 0.1
phases:
  install:
    commands:
      - curl -O https://bootstrap.pypa.io/get-pip.py
      - python3 get-pip.py --user
      - pip install awscli --upgrade --user
      - aws s3api list-buckets
      - aws s3 cp s3://testsandy/3.6.0.zip /opt/3.6.0.zip
      - sudo apt-get install unzip
      - sudo unzip /opt/3.6.0.zip
      - ls -l /opt/