version: 0.1
phases:
  install:
    commands:
      - curl -O https://bootstrap.pypa.io/get-pip.py
      - python3 get-pip.py --user
      - pip install awscli --upgrade --user
      - aws s3api list-buckets